"version": 1
"applications":
  "mysql-volume-example":
    "image": "mysql"
    "environment":
      "MYSQL_ROOT_PASSWORD": "clusterhq"
    "ports":
    - "internal": 3306
      "external": 3306
    "volume":
      "mountpoint": "/var/lib/mysql"
