web:
  image: binocarlos/moby-counter:latest
  environment:
     - "USE_REDIS_HOST=redis"
     - "constraint:flocker-node==0"
  links:
    - redis
  ports:
    - "80:80"
redis:
  image: redis:latest
  environment:
     - "constraint:flocker-node==0"
  volume_driver: flocker
  volumes:
     - 'mcdata:/data'
