# Copyright ClusterHQ Inc.  See LICENSE file for details.
#
# Run a subset of Flocker tests on Travis-CI.
sudo: false

dist: trusty

language: python

python: 2.7

cache:
  pip: true
  apt: true

install:
  - pip install tox awscli

env:
  - FLOCKER_BUILDER=lint
  - FLOCKER_BUILDER=docs-lint
  - FLOCKER_BUILDER=docs-spelling
  - FLOCKER_BUILDER=docs-linkcheck
  - FLOCKER_BUILDER=docs-html

matrix:
  allow_failures:
  - env: FLOCKER_BUILDER=docs-lint
  - env: FLOCKER_BUILDER=docs-linkcheck

script:
  - .travis/script

after_script:
  - .travis/after_script

addons:
  apt:
    packages:
    - python-enchant

# Only run tests on push on a few branches.
# Test on PR should be execute for all branches and forks.
branches:
  only:
  - master
  - /^release\/flocker-.*$/
