# Copyright ClusterHQ Inc.  See LICENSE file for details.
#
# Run a subset of Flocker tests on Travis-CI.
sudo: false

dist: trusty

language: python

python: 2.7

cache: pip

install:
  - pip install tox

env:
  - TOX_ENV=lint
  - TOX_ENV=docs-lint
  - TOX_ENV=docs-spelling
  - TOX_ENV=docs-linkcheck
  - TOX_ENV=docs-html

matrix:
  allow_failures:
  - env: TOX_ENV=docs-lint
  - env: TOX_ENV=docs-linkcheck

script:
  - tox -e $TOX_ENV

addons:
  apt:
    packages:
    - python-enchant
