# Copyright ClusterHQ Inc.  See LICENSE file for details.
#
# Run a subset of Flocker tests on Travis-CI.
sudo: false

dist: trusty

language: python

python: 2.7

cache: pip

install:
  - pip install tox

env:
  - FLOCKER_BUILDER=lint
  - FLOCKER_BUILDER=docs-lint
  - FLOCKER_BUILDER=docs-spelling
  - FLOCKER_BUILDER=docs-linkcheck
  - FLOCKER_BUILDER=docs-html

matrix:
  allow_failures:
  - env: FLOCKER_BUILDER=docs-lint
  - env: FLOCKER_BUILDER=docs-linkcheck

script:
  - $TRAVIS_BUILD_DIR/.travis/script

addons:
  apt:
    packages:
    - python-enchant
